Effect.new("Raise Dead Cooldown", 9009) do
  def type
    "timer"
  end
  def availability
    "all"
  end
  def duration
    s = Spell['Raise Dead Cooldown']; if s.active?; s.timeleft; else; if reget.any? { |line| line =~ /^You have a foreboding sense of darkness enveloping your soul as you realize [A-Z][a-z]+ has died while both of you are still soul linked!  You can sense the tugging of [A-Z][a-z]+'s? soul clinging on to life, pulling you headlong into the long dark\.  It takes every ounce of spiritual energy you have to sever the link and claw yourself back to the world of the living!  You feel empty and torpid, unable to focus your spiritual self\./ }; 60.0; else; 5-(Skills.slblessings/60.0)+0.05; end; end
  end
  def start_messages
   Regexp.union(
      %r{Moisture beads upon your skin and you feel your eyes cloud over with the darkness of a rising storm\.  Power builds upon the air, and when you utter the last syllable of your spell thunder rumbles from your lips\.  The sound ripples upon the air, colliding with [A-Z][a-z]+'s prone form, and a brilliant flash transfers the spiritual energy between you\.},
      %r{You have a foreboding sense of darkness enveloping your soul as you realize [A-Z][a-z]+ has died while both of you are still soul linked!  You can sense the tugging of [A-Z][a-z]+'s? soul clinging on to life, pulling you headlong into the long dark\.  It takes every ounce of spiritual energy you have to sever the link and claw yourself back to the world of the living!  You feel empty and torpid, unable to focus your spiritual self\.},
      %r{You are unable to gather enough strength to focus your spirit\.  Perhaps you should rest some\.},
      %r{Deep and resonating, you feel the chant that falls from your lips instill within you with the strength of your faith\.  You crouch beside [A-Z][a-z]+ and gently lift (?:he|she|him|her) into your arms, your muscles swelling with the power of your deity, and cradle (?:him|her) close to your chest\.  Strength and life momentarily seep from your limbs, causing them to feel laden and heavy, and you are overcome with a sudden weakness\.  With a sigh, you are able to lay [A-Z][a-z]+ back down\.},
      %r{Moisture beads upon your skin and you feel your eyes cloud over with the darkness of a rising storm\.  Power builds upon the air and when you utter the last syllable of your spell thunder rumbles from your lips\.  The sound ripples upon the air, and colling with [A-Z][a-z']+ prone form and a brilliant flash transfers the spiritual energy between you\.},
      %r{Lifting your finger, you begin to chant and draw a series of conjoined circles in the air\.  Each circle turns to mist and takes on a different hue - white, blue, black, red, and green\.  As the last ring is completed, you spread your fingers and gently allow your tips to touch each color before pushing the misty creation towards [A-Z][a-z]+\.  A shock of energy courses through your body as the mist seeps into [A-Z][a-z']+ chest and life is slowly returned to (?:his|her) body\.},
      %r{Crouching beside the prone form of [A-Z][a-z]+, you softly issue the last syllable of your chant\.  Breathing deeply, you take in the scents around you and let the feel of your surroundings infuse you\.  With only your gaze, you track the area and recreate the circumstances of [A-Z][a-z']+ within your mind\.  Touching [A-Z][a-z]+, you follow the lines of the web that holds (?:his|her) soul in place and force it back into (?:his|her) body\.  Raw energy courses through you and you feel your sense of justice and vengeance filling [A-Z][a-z]+ with life\.},
      %r{Murmuring softly, you call upon your connection with the Destroyer,? and feel your words twist into an alien, spidery chant\.  Dark shadows laced with crimson swirl before your eyes and at your forceful command sink into the chest of [A-Z][a-z]+\.  The transference of energy is swift and immediate as you bind [A-Z][a-z]+ back into (?:his|her) body\.},
      %r{Rich and lively, the scent of wild flowers suddenly fills the air as you finish your chant, and you feel alive with the energy of spring\.  With renewal at your fingertips, you gently touch [A-Z][a-z]+ on the brow and revel in the sweet rush of energy that passes through you into (?:him|her|his)\.},
      %r{Breathing slowly, you extend your senses towards the world around you and draw into you the very essence of nature\.  You shift your gaze towards [A-z][a-z]+ and carefully release the energy you've drawn into yourself towards (?:him|her)\.  A rush of energy briefly flows between the two of you as you feel life slowly return to (?:him|her)\.},
      %r{Your surroundings grow dim\.\.\.you lapse into a state of awareness only, unable to do anything\.\.\.},
      %r{Murmuring softly, a mournful chant slips from your lips and you feel welts appear upon your wrists\.  Dipping them briefly, you smear the crimson liquid the leaks from these sudden wounds in a thin line down [A-Z][a-z']+ face\.  Tingling with each second that your skin touches (?:his|hers), you feel the transference of your raw energy pass into [A-Z][a-z]+ and momentarily reel with the pain of its release\.  Slowly, the wounds on your wrists heal, though a lingering throb remains\.},
      %r{Emptying all breathe from your body, you slowly still yourself and close your eyes\.  You reach out with all of your senses and feel a film shift across your vision\.  Opening your eyes, you gaze through a white haze and find images of [A-Z][a-z]+ floating above his prone form\.  Acts of [A-Z][a-z]'s? past, present, and future play out before your clouded vision\.  With conviction and faith, you pluck a future image of [A-Z][a-z]+ from the air and coax (?:he|she|his|her) back into (?:he|she|his|her) body\.  Slowly, the film slips from your eyes and images fade away\.},
      %r{Thin at first, a fine layer of rime tickles your hands and fingertips\.  The hoarfrost smoothly glides between you and [A-Z][a-z]+, turning to a light powder as it traverses the space\.  The white substance clings to [A-Z][a-z]+'s? eyelashes and cheeks for a moment before it becomes charged with spiritual power, then it slowly melts away\.},
      %r{As you begin to chant,? you notice the scent of dry, dusty parchment and feel a cool mist cling to your skin somewhere near your feet\.  You sense the ethereal tendrils of the mist as they coil about your body and notice that the world turns to a yellowish hue as the mist settles about your head\.  Focusing on [A-Z][a-z]+, you feel the transfer of energy pass between you as you return (?:him|her) to life\.},
      %r{Wrapped in an aura of chill, you close your eyes and softly begin to chant\.  As the cold air that surrounds you condenses you feel it slowly ripple outward in waves that turn the breath of those nearby into a fine mist\.  This mist swiftly moves to encompass you and you feel a pair of wings arc over your back\.  With the last words of your chant, you open your eyes and watch as foggy wings rise above you and gently brush against [A-Z][a-z]+\.  As they dissipate in a cold rush against [A-Z][a-z]+, you feel a surge of power spill forth from you and into (?:him|her)\.},
      %r{Low and monotonous, you begin a chant to draw [A-Z][a-z]+ back to life and feel the deep shadows of the area rise to meet you\.  Falling upon you like a cloak of darkness, the twisting, inky blackness transforms into the visage of a jackal from a once-forgotten nightmare\.  Sweeping from your body into [A-Z][a-z]+'s?, the raw energy of your prayer transfers into (?:his|her) prone form\.  Slowly, the shadows recede back into the surrounding area\.},
    )
  end
  def end_messages
    Regexp.union(
      %r{The feeling of weakness leaves you\.  Your spirits are somewhat rejuvenated\.},
    )
  end
end