Effect.new("Miracle Cooldown", 9044) do
  def type
    "timer"
  end
  def availability
    "all"
  end
  def duration
    dur = 1440; [ 4, 9, 15, 22, 30, 39, 49, 60, 72, 85, 99, 114, 130, 147, 165, 184 ].each { |num| dur -= 60 if Skills.slreligion >= num }; dur
  end
  def start_messages
   Regexp.union(
      %r{Spidery and incomprehensible words reach you, and are given life by an aged, bodiless voice that carries with it the scent of dusty tomes and candle tallow\.  A point of dark light appears high over your body and expands to form a yellowed eye with a slit pupil\.  With each uttered syllable the eye's iris contracts and the meaning of the words that wrap you become clear\.  "You still have much more to learn," they say, and before you the eye explodes in a blinding, fiery light\.},
      %r{You feel a tingling at the edges of your perception and the air comes alive with a feeling of raw power\. You sense something greater than yourself tugging on your spirit\. As the power grows in intensity, you feel it draw you closer to your lifeless body and you marvel as it ushers your spirit forward\. An extremely bright nimbus floods you as your spirit sinks into your body, which begins to fill with life\.},
      %r{Silence descends upon the room and a double\-headed serpent slithers to you\. Each of its heads moves of its own accord, and slit\-pupiled eyes take in everything as they wind a sinuous path up your prone form\. As it reaches your chest, it lifts its heads up high and begins to sway from side to side in a hypnotic pattern\. "You have learned the ssssacrifice issss everything, now we ssssacrifice oursssselves sssso that you may teach otherssss," the one head says before striking the other head at the neck\. In one swift, painless bite, the head is severed and the open neck falls upon you, its lifeblood draining into your mouth\. Moments pass as the ferric taste of the serpent's sacrifice fills you, and then suddenly it disappears\.},
      %r{As the air stirs, you feel your spirit drawn to the heavy scent of the ocean and feel a deep sense of peace\. Clouds move into the area, their murky depths heavy with rain unshed and you can see lightning dancing within them\. The pressure builds all around you until suddenly, the heavens release dozens of slender blue bands of lightning\. The lightning fills your body with its energy and the very air around you seems to tingle with it\. Moments later, the lightning is gone and the clouds soon follow\.},
      %r{Odd whirls and metallic clangs herald the arrival of a dwarf crafted entirely of bronze\. The strange, mechanical man moves with jerky movements to a position beside the prone form of Cleric and begins to tinker with his appearance and clothing\. At first, nothing seems to come of the strange bronze creature's meddling, but slowly color returns to Cleric's face\. Steam billowing from its ears, the metallic dwarf straightens and teeters from the area, dissipating as it moves\.},
      %r{Stealing all sound as it travels to you, a soft zephyr gently caresses your skin and you sense the frigid brush of final death near at hand\. A tug on your spirit heralds the arrival of impossibly long feathers in shades of white, grey, and black, as they appear before you and coalesce into a beautiful insubstantial being\. It lifts you up into its arms and you feel as if you have found home in its embrace\.},
      %r{Filling your spirit with a deep anger, a long discordant horn blast drowns your senses and sets your lifeless flesh to vibrating with its wild call\. An enormous hunting hound bearing an angry look of focus bounds towards you\. You feel its front paws forcibly slam into your chest and watch the beast disappear deep within you with the cry of a wild hunt falling from its parted lips\. Slowly, the sound of the horn echoes into silence\.},
      %r{Time stills around you, and you feel your spirit drawn forward by a pale ethereal light which quickly transforms into a translucent woman\. She moves to your side and withdraws two crimson oak leaves and an acorn from her basket\. You hear her soft prayer as she places the leaves upon your eyes and presses the acorn past your lips\. She turns her eyes to the sky, her arms rising in supplication, and then lays her hands briefly on your chest\. Instantly, warmth floods your limbs and the woman returns to the pale light\.},
      %r{Large and ethereal, rectangular talismans rise from the ground to form a ring around your lifeless form\. Each talisman is carved with a different word and glows with a brilliant light\. One by one, the talismans tumble into you\. As the first falls upon you, you are filled with a deep sense of Honor, the second reminds you of Valor in battle, and the third causes your spirit to surge with Hope, while the fourth binds you with the strength of your Faith\. The remaining two tumble into you simultaneously and, in a flash of white light, you absorb them all\.},
      %r{Creating a myriad of colorful whorls in the air, a flock of small rainbow-winged lizards swirls towards you and you are filled with a deep connection to them\. Diving and darting, they cavort above your corpse in an intricate dance that is breathtaking to behold\. As they dance, their wings shimmer and shed multi-colored sparks that rain down upon your body\. With each spark that alights upon your flesh, you are filled with a tingling sensation that draws your spirit deep into your body\. The aerial display ends in one final loop and the rainbow\-winged lizards dart off into the distance, only to wink out of sight a moment later\.},
      %r{Your spirit feels a sudden stirring in the air above your lifeless body and moments later a brilliantly white owl appears out of nowhere\. It spreads its wings and you hear the audible crack of the air as they expand, lifting the owl in a lazy spiral above you\. The bird's unblinking gaze falls upon you and you feel a deep connection with it before it gives three mighty beats of its wings and surges high into the sky and disappears\.},
      %r{Distant and echoing, the sound of keys jingling strikes a familiar chord within you as it precedes the sound of a heavy metal gate slamming shut\. Pale snowflakes drift through the air and settle upon your lifeless body\. As the snow accumulates into a thin, chilling layer, you distinctly hear the somber voice of a female speaking softly in your ear\. "The gates are closed to you for now, my child," she says, and several moments later the snow seeps into your skin, leaving you chilled and damp\.},
      %r{Punctuating the sudden calm of the area, the sound of slithering is quickly followed by a long, sibilant hiss\. Winding a sinuous pattern to your head, an impossibly large copper-head snake with emerald green eyes begins to hiss at you\. "There are more liessss to sssspread, and deathssss to ssssteal," it says, and then swiftly raises high into the air to gaze down at you\. Faster than the blink of an eye, the serpent dives into your chest and disperses into a shimmering green mist that seeps into your skin\.},
      %r{Dark clouds swirl across your prone form and the area is plunged into darkness\. The hair on your body stands on end and a deep pressure builds around your spirit, threatening to consume it\. Blue lightning lances through the air, heralding an ear-shattering ripple of thunder, and at the edge of your senses you feel the demonic horde surging forward to take you\. Each sizzling bolt strikes your chest repeatedly for several moments and the horde closes in on you until every last one of them is absorbed by your spirit\.},
      %r{Wraithlike mourners suddenly slip free of the shadows and form a tight ring around you\. Silvery tears slip from their faces to splash ineffectively against your lifeless body, and the blood that stains their white garments trickles in a splash across your face\. They kneel in a tight ring about you, obscuring your view of the world beyond, and you feel a deep connection to them\. "There is yet more pain to release," they seem to tell you before their lips part in a deafening keen of anguish that shatters their ethereal forms\.},
      %r{A playful feeling sweeps over you as a fuzzy pair of otters fills your vision\. Clutched in their teeth are midnight blue mussels, which they hold tightly in place as they comically bounce and leap around you\. They playfully paw at your lifeless chest, begging with their furry faces, and you sense they want you to come and play\. As if sensing you cannot, they curl their sleek, wet forms briefly around your head and nuzzle against your neck for several moments\. Then, they carefully drop the mussels upon your chest\. A brief, child-like joy fills you as the mussels sink into your lifeless body, and the otters turn as one to slide out of sight on their slippery bellies\.},
      %r{Shadows slant across the ground as they slither toward you and a deep chill touches your spirit\. As the shadows writhe in a thick mass of darkness over your body, you distinctly hear a quiet whisper in your ear, "This was not the death I had in mind for you\." A flash of light tears across your vision as it is consumed by the image of a cracked white skull\.},
      %r{Regal and proud, a broad-shouldered ethereal lion strides towards your lifeless form and you are filled with a sense of power and glory\. As it moves towards you, its mane begins to shimmer with licking flames that resemble the rays of the sun\. It lowers its gaze to you and you feel yourself drawn into their amber depths\. The golden beast lifts a paw to your chest and a wave of warmth floods your limbs\. As the light grows, the lion begins to dissipate into a golden nimbus that sinks into your body\.},
      %r{The sounds of night drift to your ears and you feel a deep lassitude flood your spirit\. At the edge of your vision the pale white beautiful image of a unicorn begins to take shape\. It paws at the air, its silver hooves creating sparks of light that twinkle like a thousand stars\. As it lowers the horn to touch your forehead you feel a deep sense of peace that intensifies as a silver nimbus blankets you\. The unicorn and the nimbus disappear at once, and you feel yourself waking slowly from a dream\.},
      %r{Shadows lengthen and grow around you until their edges are sharp and twisted\. Macabre and ungraceful, they slink with jerky movements toward you as their depths are briefly illuminated by countless yellowed eyes set into the faces of a thousand horrors\. They snarl as they writhe across your prone form, their maws snapping ineffectively at your flesh\. One by one, they twist and squirm into your slack jaw and fill you with bitter madness\.},
      %r{Silver motes of light cavort upon the air, their movements turning into a twisted dance that is punctuated by the sound of dozens of laughing voices\. Deep in your spirit, you feel a binding connection to their mirth\. Converging above you, the light transforms in a slender crescent moon that begins to whirl\. At one moment, full, and then the next, a sliver, the faster the moon spins, the louder the laughter gets\. Suddenly, the light ceases all movement and explodes into a brilliant shower of silver sparks accompanied by laughter for several moments\.},
    )
  end
end